# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54dd868960bee68df3fb8af91aa04c790ee7dfe09cf13cb2c32eb925a7032b3da51447dc0cf942c9e2581533c25c24a5690a10be77c7309dee9f0fbe6bea7399

test:
  secret_key_base: 274879aa9a5c4348895c0bd8faeba3f9d0686c5484dba4f22a2cd55a70b6cdf8b1adb14f9c54d319476e398ab8772a88b2797dc8768b41b1d3fbe74356910713

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
